### ISSUE TITLE
Q: ethereum transaction in millionaires problem demo

### ISSUE THREAD

**Issue by pblin** [enigmampc/enigma-template-dapp#2]
How is EVM transaction signed when making a contract call?

**Comment by lacabra** [comment]
They are signed automatically by the underlying Web3 layer without any user interaction because in this docker network we are using the truffle/ganache accounts that are unlocked by default, and thus Web3 has all the permissions required to sign the required transactions and publish them to the network automatically.

For example, refer to this contract call: 
https://github.com/enigmampc/enigma-template-dapp/blob/73e24eb9d03da77785544b1d3e92a371dffd3a82/client/src/MillionairesProblemWrapper.js#L60
which calls this function on the MillionaireProblem deployed on the Ethereum development network:
https://github.com/enigmampc/enigma-template-dapp/blob/73e24eb9d03da77785544b1d3e92a371dffd3a82/contracts/MillionairesProblem.sol#L36

Please refer to the documentation for Web3 contract methods: https://github.com/ethereum/wiki/wiki/JavaScript-API#contract-methods 
We are using the call to the method directly, which under the hood determines whether to issue a `call` or a `sendTransaction` based on the method type (the latter in this case). 

I'm closing this issue as I believe the above explanation addresses the original question, but please reopen it if that's not the case.

Thank you.
